---
# defaults file for prep-management-node
kolla_ansible_repo: "git+https://opendev.org/openstack/kolla-ansible@master"
deps: [python3-dev, libffi-dev, gcc, libssl-dev]
venv_deps: [python3-venv]
venv_wrapper: "/opt/venv/kolla/bin/pyvenv"

config_dirs:
  - "/etc/kolla/config"
  - "/etc/kolla/config/cinder"
  - "/etc/kolla/config/cinder/cinder-backup"
  - "/etc/kolla/config/cinder/cinder-volume"
  - "/etc/kolla/config/glance"
  - "/etc/kolla/config/nova"

ceph_keyring_files:
  - "/etc/kolla/config/cinder/cinder-backup/ceph.client.cinder-backup.keyring"
  - "/etc/kolla/config/cinder/cinder-backup/ceph.client.cinder.keyring"
  - "/etc/kolla/config/cinder/cinder-volume/ceph.client.cinder.keyring"
  - "/etc/kolla/config/glance/ceph.client.glance.keyring"
  - "/etc/kolla/config/nova/ceph.client.nova.keyring"
  - "/etc/kolla/config/nova/ceph.client.cinder.keyring"

ceph_conf_files:
  - "/etc/kolla/config/cinder/cinder-backup/ceph.conf"
  - "/etc/kolla/config/cinder/cinder-volume/ceph.conf"
  - "/etc/kolla/config/glance/ceph.conf"
  - "/etc/kolla/config/nova/ceph.conf"

ceph_keyring_temp_files: 
  - "/tmp/ceph-keyrings/ceph.client.cinder-backup.keyring"
  - "/tmp/ceph-keyrings/ceph.client.cinder.keyring"
  - "/tmp/ceph-keyrings/ceph.client.glance.keyring"
  - "/tmp/ceph-keyrings/ceph.client.nova.keyring"