---
- name: Prepare OpenStack nodes
  hosts: openstack_nodes
  gather_facts: true
  become: true
  roles:
    - role: prep_openstack_nodes

- name: Deploy Ceph
  hosts: storage_nodes
  gather_facts: true
  become: true
  roles:
    - role: deploy_ceph

- name: Install Kolla-Ansible
  hosts: management_nodes
  gather_facts: true
  become: true
  roles:
    - role: install_kolla

- name: Deploy OpenStack
  hosts: management_nodes
  gather_facts: true
  become: true
  roles:
    - role: deploy_openstack
