---
- name: Install venv dependencies
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop: "{{ venv_deps }}"

- name: Create kolla virtual environment
  ansible.builtin.command: python3 -m venv {{ kolla_venv_path }}
  args:
    creates: "{{ kolla_venv_path }}/bin/activate"

- name: Copy venv wrapper script
  ansible.builtin.template:
    src: "{{ playbook_dir }}/roles/prep-management-node/templates/pyvenv.j2"
    dest: "{{ venv_wrapper }}"
    mode: '0755'

- name: Kolla venv pip tasks
  vars:
    ansible_python_interpreter: "{{ venv_wrapper }}"
  block:
    - name: Update pip
      ansible.builtin.command: pip install --upgrade pip

    - name: Install ansible-core
      ansible.builtin.command: pip install 'ansible-core>=2.17'
