- name: Deploy OpenStack using Kolla Ansible
  vars:
    ansible_python_interpreter: "{{ venv_wrapper }}"
  block:
    - name: Bootstrap servers
      command: kolla-ansible bootstrap-servers -i /etc/kolla/inventory
    
    - name: Prechecks
      command: kolla-ansible prechecks -i /etc/kolla/inventory

    - name: Deploy Kolla
      command: kolla-ansible deploy -i /etc/kolla/inventory

    - name: Install OpenStack CLI client
      command: pip install python-openstackclient
    
    - name: Run post-deploy
      command: kolla-ansible post-deploy -i /etc/kolla/inventory
    
    - name: Run init-runonce
      command: ./share/kolla-ansible/init-runonce
      args:
        chdir: "{{ venv_path }}"
