---
- name: Update the system
  apt:
    update_cache: yes
    upgrade: dist
    cache_valid_time: 3600

- name: Install dependencies
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ deps }}"