[compute_nodes]
compute

[storage_nodes]
storage

[controller_nodes]
controller

[management_nodes]
controller

[openstack_nodes:children]
controller_nodes
compute_nodes
storage_nodes

[portal_nodes]
portal

[all:vars]
ansible_python_interpreter=/usr/bin/python3.12

[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/bin/python3
