---
k3s_cluster:
  children:
    server:
      hosts:
        10.0.1.4:
          ansible_host: 192.168.0.103
    agent:
      hosts:
        10.0.1.3:
          ansible_host: 192.168.0.102
          extra_agent_args: "--node-ip=10.0.1.3 --node-external-ip=10.0.1.3"
        10.0.1.2:
          ansible_host: 192.168.0.101
          extra_agent_args: "--node-ip=10.0.1.2 --node-external-ip=10.0.1.2"

  vars:
    ansible_port: 22
    ansible_user: sysoperator
    ansible_ssh_private_key_file: ~/.ssh/openstack_key
    ansible_become_pass: sysoperator
    k3s_version: v1.36.1+k3s1
    token: "{{ vault_k3s_token }}"
    api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
    extra_server_args: "--disable=traefik --node-external-ip=10.0.1.4 --node-ip=10.0.1.4"
