---
- name: Make sure we have a 'wheel' group
  ansible.builtin.group:
    name: wheel
    state: present

- name: Allow wheel group to sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    line: '%wheel ALL=(ALL) NOPASSWD: ALL'
    state: present
    validate: 'visudo -cf %s'

- name: Create sysoperator user
  ansible.builtin.user:
    name: sysoperator
    group: wheel
    password: "{{ sysoperator_password | password_hash('sha512') }}"
    shell: /bin/bash
    create_home: true
    state: present
    update_password: on_create
