ethernets:
  - link: 'ens18'
    addresses: ['10.1.0.196/24']
    routes:
      - to: 'default'
        via: '10.1.0.1'
    nameservers:
      addresses: ['8.8.8.8', '1.1.1.1']
  - link: 'ens19'
    addresses: ['192.168.100.196/24']
  - link: 'ens20'
    addresses: ['192.168.200.196/24']