---
galaxy_info:
  author: George-Alexandru Tudurean
  description: Configure kolla and deploy OpenStack services via kolla-ansible
  license: MIT
  min_ansible_version: "2.17"
  galaxy_tags: []
dependencies: []
